### ISSUE TITLE
Bump for wagtail 2.14.1

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail-airtable#34]
It looks like wagtail 2.14.1 is not currently allowed, can this version number be bumped?

**Comment by KalobTaulien** [comment]
@Pomax setup.py is only looking for `wagtail>=2.6`. Any chance this is coming from `djangorestframework>=3.11.0,<=3.12.2`?

**Comment by Pomax** [comment]
You're right, this deals with 2.14.1 just fine, turns out the actual culprit was wagtail-localize-git - requirement errors: super clear text!
